export enum InputTypeEnum {
    TEXT, NUMBER, SELECT, DATE, COUNTRY, TIME, TEXTAREA, CHECKBOX, RADIO, LIST
}

export enum AddressOwner {
    STUDENT, TEACHER, ADMIN, GUARDIAN, ENROLLMENT
}

export enum IndividualType {
    STUDENT, TEACHER, EMPLOYEE, GUARDIAN, ENROLLMENT
}

export enum UpdateType {
    ADDRESS, HEALTH, GUARDIAN, INFO, TEACHER, ASSIGNMENT
}
