export enum InputTypeEnum {
    TEXT, PASSWORD, NUMBER, SELECT, DATE, COUNTRY, TIME, TEXTAREA, CHECKBOX, RADIO, LIST
}

export enum AddressOwner {
    STUDENT, TEACHER, EMPLOYEE, GUARDIAN, ENROLLMENT, SCHOOL
}

export enum IndividualType {
    EMPLOYEE, GUARDIAN, TEACHER, STUDENT
}

export enum UpdateType {
    ADDRESS, HEALTH, GUARDIAN, INFO, TEACHER, ASSIGNMENT, EMPLOYEE, SCHOOL,
    ACADEMIC_YEAR, GRADE, DEPARTMENT, USER
}
