export enum InputTypeEnum {
    TEXT, NUMBER, SELECT, DATE, COUNTRY, TEXTAREA, CHECKBOX, RADIO, LIST
}

export enum AddressOwner {
    STUDENT, TEACHER, ADMIN, GUARDIAN, ENROLLMENT
}

export enum IndividualType {
    STUDENT, TEACHER, EMPLOYEE, GUARDIAN, ENROLLMENT
}
