export type { AcademicYear } from './domain/academicYear.ts'
export type { Assignment } from './domain/assignment.ts'
export type { Address } from './domain/address'
export type { Attendance } from './domain/attendance'
export type { Classe } from './domain/classe'
export type { Course } from './domain/course'
export type { Department } from './domain/department'
export type { Enrollment } from './domain/enrollment'
export type { Exam } from './domain/exam'
export type { Grade } from './domain/grade'
export type { Guardian } from './domain/guardian'
export type { HealthCondition } from './domain/healthCondition'
export type { Planning } from './domain/planning'
export type { Schedule } from './domain/schedule'
export type { School } from './domain/school'
export type { Score } from './domain/score.ts'
export type { Student } from './domain/student'
export type { Teacher } from './domain/teacher'
export type {CourseProgram} from './domain/courseProgram'
export { toGuardianSchema } from './domain/guardian'