export type { AcademicYear } from './domain/academicYear.ts'
export type { Assignment, AssignmentFilterProps, AssignmentTypeAverage } from './domain/assignment.ts'
export type { Address } from './domain/address'
export type { Attendance } from './domain/attendance'
export type { Classe } from './domain/classe'
export type { ClasseStudentBoss } from './domain/classeStudentBoss'
export type { ClasseTeacherBoss } from './domain/classeTeacherBoss'
export type { Course } from './domain/course'
export type { Department, DBoss } from './domain/department'
export type { Enrollment } from './domain/enrollment'
export type { toEnrollment } from './domain/enrollment'
export type { Employee, EmployeeContract, ContractStatus, SalaryBasis, JobTitle } from './domain/employee'
export { StaffRole, ContractStatusEnum, SalaryBasisEnum } from './domain/employee'
export type { Exam, ExamData, ExamProgress, ExamResponse, ExamView, NestedExamView, ExamStatistics, SubjectAssignment, TypedAssignment } from './domain/exam'
export type { ExamType} from './domain/examType'
export type { Grade } from './domain/grade'
export type { Guardian } from './domain/guardian'
export { toGuardianSchema } from './domain/guardian'
export type { HealthCondition } from './domain/healthCondition'
export type { Planning } from './domain/planning'
export type { Schedule, ScheduleCalendarEvent } from './domain/schedule'
export type { School } from './domain/school'
export type { Score } from './domain/score.ts'
export { initExamData } from './domain/score.ts'
export type { Student } from './domain/student'
export type { Teacher, TeacherCourses, TeacherClasses, TeacherSchoolAffiliate, TeacherCourseUpdateRequest, TeacherClassUpdateRequest, AffiliationStatus } from './domain/teacher'
export { AffiliationStatusEnum, OperationType } from './domain/teacher'
export type { CourseProgram, ProgramTopic, CourseProgramResponse, ProgramTiming, SemesterProgram } from './domain/courseProgram'
export { ProgramStatus, isInProgress, statusConfig, isFinished, isDrafted, isDebut, hasDebuted } from './domain/courseProgram'
export type { Reprimand, ReprimandFilterProps } from './domain/reprimand'
export { AVATAR_PALETTE } from './domain/reprimand'
export type { Individual, IndividualType, individualTypeToUserType } from './domain/individual'
export type { Punishment } from './domain/punishment'
export type { Semester, SemesterTemplate } from './domain/semester'
export type { TeacherClassCourse } from './domain/TeacherClassCourse'
export type { Report, ReportStatus, ReportStatusEnum, reportStatusColors } from './domain/report.ts'