export type { AcademicYear } from './domain/academicYear.ts'
export type { Assignment } from './domain/assignment.ts'
export type { Address } from './domain/address'
export type { Attendance } from './domain/attendance'
export type { Classe } from './domain/classe'
export type { ClasseStudentBoss } from './domain/classeStudentBoss'
export type { ClasseTeacherBoss } from './domain/classeTeacherBoss'
export type { Course } from './domain/course'
export type { Department, DBoss } from './domain/department'
export type { Enrollment } from './domain/enrollment'
export type { Employee } from './domain/employee'
export type { Exam } from './domain/exam'
export type { ExamType } from './domain/examType'
export type { Grade } from './domain/grade'
export type { Guardian } from './domain/guardian'
export type { HealthCondition } from './domain/healthCondition'
export type { Planning } from './domain/planning'
export type { Schedule } from './domain/schedule'
export type { School } from './domain/school'
export type { Score } from './domain/score.ts'
export type { Student } from './domain/student'
export type { Teacher } from './domain/teacher'
export type {CourseProgram} from './domain/courseProgram'
export type {Reprimand} from './domain/reprimand'
export type {Individual} from './domain/individual'
export type {Punishment} from './domain/punishment'
export type {Semester, SemesterTemplate} from './domain/semester'
export type {TeacherClassCourse} from './domain/TeacherClassCourse'
export { toGuardianSchema } from './domain/guardian'