export const BROWSERS = [
    "Google Chrome",
    "Mozilla Firefox",
    "Microsoft Edge",
    "Apple Safari",
    "Opera",
    "Brave",
    "Vivaldi",
    "Tor Browser",
    "Maxthon",
    "Pale Moon",
    "Waterfox",
    "Midori",
    "GNOME Web (Epiphany)",
    "Falkon",
    "SRWare Iron",
    "Comodo Dragon",
    "Avast Secure Browser",
    "Epic Privacy Browser",
    "Colibri",
    "Samsung Internet",
    "UC Browser",
    "QQ Browser",
    "Opera Mini",
    "Kiwi Browser",
    "Dolphin Browser",
    "Puffin Browser",
    "Phoenix Browser",
    "Internet Explorer",
    "Netscape Navigator",
    "Google Daydream Browser",
    "BlackBerry Browser",
    "Skyfire",
    "RockMelt",
    "Camino"
]
