export enum Gender {
    HOMME = 'HOMME',
    FEMME = 'FEMME',
    GAY = 'GAY',
    LESBIENNE = 'LESBIENNE',
    NON_BINAIRE = 'NON_BINAIRE',
    FLUIDE = 'FLUIDE',
    QUEER = 'QUEER',
    AGENDER = 'AGENDER',
    BIGENRE = 'BIGENRE',
    PANGENRE = 'PANGENRE',
    TRAVESTI = 'TRAVESTI'
}