export enum ReprimandType {
    INSUBORDINATION = 'INSUBORDINATION',
    TRUANCY = 'ABSENTÉISME',
    CHEATING = 'TRICHERIE',
    DISRESPECT = 'IRRESPECT',
    VANDALISM = 'VANDALISME',
    VIOLENCE = 'VIOLENCE',
    BULLYING = 'INTIMIDATION',
    SUBSTANCE = 'SUBSTANCE',
    FRAUD = 'FRAUDE',
    NONCOMPLIANCE = 'NON-CONFORMITÉ',
}