export enum SectionType {
    MATERNELLE = 'MATERNELLE',
    PRIMAIRE = 'PRIMAIRE',
    COLLEGE = 'COLLEGE',
    LYCEE = 'LYCEE',
    INSTITUT = 'INSTITUT',
    INSTITUT_TECHNIQUE = 'INSTITUT_TECHNIQUE',
    UNIVERSITE = 'UNIVERSITE',
    LYCEE_GENERALE = 'LYCEE_GENERALE',
    LYCEE_TECHNIQUE = 'LYCEE_TECHNIQUE',
    LYCEE_TECHNIQUE_COMMERCIALE = 'LYCEE_TECHNIQUE_COMMERCIALE',
    LYCEE_TECHNIQUE_INDUSTRIEL = 'LYCEE_TECHNIQUE_INDUSTRIEL',
    LYCEE_PROFESSIONEL = 'LYCEE_PROFESSIONEL',
}