export enum SectionType {
    MATERNELLE = 'MATERNELLE',
    PRIMAIRE = 'PRIMAIRE',
    COLLEGE = 'COLLEGE',
    LYCEE = 'LYCEE',
    INSTITUT = 'INSTITUT',
    INSTITUT_TECHNIQUE = 'INSTITUT TECHNIQUE',
    UNIVERSITE = 'UNIVERSITE',
    LYCEE_GENERALE = 'LYCEE GENERALE',
    LYCEE_TECHNIQUE = 'LYCEE TECHNIQUE',
    LYCEE_TECHNIQUE_COMMERCIALE = 'LYCEE TECHNIQUE COMMERCIALE',
    LYCEE_TECHNIQUE_INDUSTRIEL = 'LYCEE TECHNIQUE INDUSTRIEL',
    LYCEE_PROFESSIONEL = 'LYCEE PROFESSIONEL',
}