export { AcademicForm } from "./components/AcademicForm.tsx";
export { AttachmentForm } from "./components/AttachmentForm.tsx";
export { AttendanceAnalysis } from "./components/AttendanceAnalysis.tsx";
export { GuardianDetails } from "./components/GuardianDetails.tsx";
export { GuardianForm } from "./components/GuardianForm.tsx";
export { StudentAttendance } from "./components/StudentAttendance.tsx";
export { StudentClasse } from "./components/StudentClasse.tsx";
export { StudentEditDrawer } from "./components/StudentEditDrawer.tsx";
export { StudentExam } from "./components/StudentExam.tsx";
export { StudentDiscipline } from "./components/StudentDiscipline.tsx";
export { StudentInfo } from "./components/StudentInfo.tsx";
export { StudentActionLinks } from "./components/StudentActionLinks.tsx";
export { StudentResult } from "./components/StudentResult.tsx"
export { RemoveStudent } from "./components/RemoveStudent.tsx"