export {TeacherAcademicForm} from './component/TeacherAcademicForm.tsx'
export {TeacherEditDrawer} from './component/TeacherEditDrawer.tsx'
export {TeacherInfo} from './component/TeacherInfo.tsx'
export {TeacherAgenda} from './component/TeacherAgenda.tsx'
export {TeacherProgram} from './component/TeacherProgram.tsx'
export {TeacherReprimand} from './component/TeacherReprimand.tsx'
export {TeacherAssignments} from './component/TeacherAssignments.tsx'